
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 29 14:53:48 CET 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENT = 13;
  public static final int FACTORIELLE = 11;
  public static final int PARFER = 10;
  public static final int MULT = 7;
  public static final int SET = 2;
  public static final int PAROUV = 9;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int EGAL = 4;
  public static final int ENTIER = 12;
  public static final int DIV = 8;
  public static final int error = 1;
  public static final int POINTV = 3;
  public static final int MOINS = 6;
}

