
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package microcobol;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 24;
  public static final int DIVIDE = 18;
  public static final int PROGRAMID = 5;
  public static final int NOMBRE = 35;
  public static final int IMAGE = 36;
  public static final int PIC = 12;
  public static final int GIVING = 21;
  public static final int DATA = 7;
  public static final int NOT = 31;
  public static final int IS = 32;
  public static final int OP = 37;
  public static final int SUBSTRACT = 16;
  public static final int MULTIPLY = 17;
  public static final int IF = 27;
  public static final int EOF = 0;
  public static final int BY = 22;
  public static final int error = 1;
  public static final int PROGRAM = 10;
  public static final int ADD = 15;
  public static final int IDENTIFICATION = 6;
  public static final int IDENT = 33;
  public static final int FROM = 23;
  public static final int MOVE = 14;
  public static final int INTO = 20;
  public static final int ENDIF = 30;
  public static final int ELSE = 29;
  public static final int STOP = 26;
  public static final int WS = 8;
  public static final int POINT = 2;
  public static final int TO = 19;
  public static final int THEN = 28;
  public static final int END = 9;
  public static final int VALUE = 13;
  public static final int CHAINE = 34;
  public static final int SECTION = 4;
  public static final int DIVISION = 3;
  public static final int RUN = 25;
  public static final int PROCEDURE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "POINT",
  "DIVISION",
  "SECTION",
  "PROGRAMID",
  "IDENTIFICATION",
  "DATA",
  "WS",
  "END",
  "PROGRAM",
  "PROCEDURE",
  "PIC",
  "VALUE",
  "MOVE",
  "ADD",
  "SUBSTRACT",
  "MULTIPLY",
  "DIVIDE",
  "TO",
  "INTO",
  "GIVING",
  "BY",
  "FROM",
  "DISPLAY",
  "RUN",
  "STOP",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "NOT",
  "IS",
  "IDENT",
  "CHAINE",
  "NOMBRE",
  "IMAGE",
  "OP"
  };
}

